### ISSUE TITLE
Export functions

### ISSUE THREAD

**Issue by dkyleward** [wsp-sag/nhtsHelper#2]
Current functions aren't exported.

**Comment by gregmacfarlane** [comment]
Have a look at the develop branch

**Comment by dkyleward** [comment]
Oh ok thanks. Is that branch ready to go, or does it need some TLC before prime time?

**Comment by gregmacfarlane** [comment]
I mean, it's been years since I looked at it. Certainly needs some kind of going over.

**Comment by chryssac** [comment]
I am closing this issue due to a long period of inactivity and because the repository is being archived
